services:
  surrealdb:
    env_file:
      - .env
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $SURREALDB_USER
      - --pass
      - $SURREALDB_PASS
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000

