stages:

  # データセットを作成
  make_dataset:
    cmd: >-
      python -m spotify_api_examples.dataset
      data/raw/favorite_artists.txt
      data/raw/dataset.json
    deps:
    - spotify_api_examples/dataset.py
    - data/raw/favorite_artists.txt
    outs:
    - data/raw/dataset.json

  # データを SurrealDB に登録
  upload_data_to_surrealdb:
    cmd: >-
      python -m spotify_api_examples.upload_data_to_surrealdb
      data/raw/dataset.json
      data/interim/last_upload_status.json
    deps:
    - spotify_api_examples/upload_data_to_surrealdb.py
    - data/raw/dataset.json
    outs:
    - data/interim/last_upload_status.json
